app:
  debug: true
  secret: verySecret
  processor-driver: docu-intel

store:
  driver: os
  location: data/

database:
  driver: inmemory
  name: database.db

document-ai:
  project-id:
  processor-id:
  location:
  credsfile: document-ai-creds.json

docu-intel:
  endpoint: 
  key: 
  model-id: 	
  api-version: 2023-07-31